name: maicosoft
description: "MaicoSoft Dashboard"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  cloud_firestore: ^6.0.1
  cloud_functions: ^6.0.4
  cpf_cnpj_validator: ^2.0.0
  firebase_auth: ^6.1.2
  firebase_auth_web: ^6.1.0
  firebase_core: ^4.1.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^6.0.0
  font_awesome_flutter: ^10.9.1
  go_router: ^16.2.1
  google_generative_ai: ^0.4.7
  http: ^1.5.0
  intl: ^0.20.2
  mask_text_input_formatter: ^2.9.0
  url_launcher: ^6.3.2
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/icons/
    - .env

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Black.ttf
          weight: 900
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
    
